name: environment_widget
description: Flutter package to set environment.
version: 1.1.0
homepage: https://github.com/TercyoStorck/environment_widget
environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
